version: 2
jobs:
  docker-splunk-test:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Build Container
          command: |
            make all
      - run:
          name: Setup Tests / Scanner Requirements
          command: |
            make test_setup
      - run:
          name: Run Vulnerability Scanner
          command: |
            make setup_and_run_clair
      - store_artifacts:
          name: Store Scanner Logs
          path: clair-scanner-logs
          destintation: clair-scanner-logs
      - run:
          name: Running tests Debian 9 
          command: make test_debian9
      - run:
          name: Running tests CentOS 7
          command: make test_centos7
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results

workflows:
  version: 2
  run_tests:
    jobs:
      - docker-splunk-test
