version: 2
jobs:
  security-scanning:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Setup python3
          command: |
            pyenv global 2.7.12 3.5.2
            python --version
            pip --version
            python3 --version
            pip3 --version
      - run:
          name: Setup Tests / Scanner Requirements
          command: |
            make test_setup
      - run:
          name: Build Container
          command: |
            make all
      - run:
          name: Run Vulnerability Scanner
          command: |
            make setup_and_run_clair
      - store_artifacts:
          name: Store Scanner Logs
          path: clair-scanner-logs
          destintation: clair-scanner-logs
      - store_artifacts:
          path: test-results
          destination: test-results
  debian10-testing:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Setup python3
          command: |
            pyenv global 2.7.12 3.5.2
            python --version
            pip --version
            python3 --version
            pip3 --version
      - run:
          name: Setup Tests / Scanner Requirements
          command: |
            make test_setup
      - run:
          name: Build Debian 10 Splunk
          command: |
            make splunk-debian-10
      - run:
          name: Build Debian 10 UF
          command: |
            make uf-debian-10
      - run:
          name: Test if image size increase
          command: make test_debian10_image_size
      - run:
          name: Run Debian 10 image tests
          command: make run_tests_debian10
          no_output_timeout: 20m
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results
  redhat8-testing:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Setup python3
          command: |
            pyenv global 2.7.12 3.5.2
            python --version
            pip --version
            python3 --version
            pip3 --version
      - run:
          name: Setup Tests / Scanner Requirements
          command: |
            make test_setup
      - run:
          name: Build Redhat 8 Splunk
          command: |
            make splunk-redhat-8
      - run:
          name: Build Redhat 8 UF
          command: |
            make uf-redhat-8
      - run:
          name: Run Redhat 8 image tests
          command: make run_tests_redhat8
          no_output_timeout: 20m
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results
  container-validation:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Setup python3
          command: |
            pyenv global 2.7.12 3.5.2
            python --version
            pip --version
            python3 --version
            pip3 --version
      - run:
          name: Setup Tests / Scanner Requirements
          command: |
            make test_setup
      - run:
          name: Build Container
          command: |
            make all
      - run:
          name: Export Build Images for Artifacts
          command: |
            make save_containers
      - run:
          name: Test Python3 installation
          command: make test_python3_all
      - run:
          name: Test Python2 as the default
          command: make test_python2_all
      - store_artifacts:
          path: test-results
          destination: test-results
workflows:
  version: 2
  build:
    jobs:
      - security-scanning
      - debian10-testing
      - container-validation
      - redhat8-testing

      
