version: 2
jobs:
  docker-splunk-test:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Build Container
          command: |
            make all
      - run:
          name: Setup Tests / Scanner Requirements
          command: |
            make test_setup
      - run:
          name: Export Build Images for Artifacts
          command: |
            make save_containers
      - run:
          name: Run Vulnerability Scanner
          command: |
            make setup_and_run_clair
      - store_artifacts:
          name: Store Scanner Logs
          path: clair-scanner-logs
          destintation: clair-scanner-logs
      - run:
          name: Running CI Tests
          command: make run_tests_debian9
          no_output_timeout: 20m
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results

workflows:
  version: 2
  run_tests:
    jobs:
      - docker-splunk-test

      
