---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: captain
  labels:
    app: splunk
    role: splunk_search_head_captain
    tier: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
      role: splunk_search_head_captain
      tier: search
  template:
    metadata:
      labels:
        app: splunk
        role: splunk_search_head_captain
        tier: search
    spec:
      hostname: captain
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - indexer.splunk.svc.cluster.local
          - search.splunk.svc.cluster.local
      containers:
        - name: captain
          image: splunk/splunk:latest
          env:
            - name: SPLUNK_HOME
              value: /opt/splunk
            - name: SPLUNK_DEFAULTS_URL
              value: http://splunk-defaults/default.yml
            - name: SPLUNK_ROLE
              value: splunk_search_head_captain
            - name: SPLUNK_PASSWORD
              value: helloworld
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_CLUSTER_MASTER_URL
              value: master
            - name: SPLUNK_INDEXER_URL
              value: indexer-0,indexer-1,indexer-2 
            - name: SPLUNK_SEARCH_HEAD_URL
              value: search-0,search-1 
            - name: SPLUNK_DEPLOYER_URL
              value: deployer
            - name: SPLUNK_SEARCH_HEAD_CAPTAIN_URL
              value: captain
            - name: DEBUG
              value: "true"
          ports:
            - name: web
              containerPort: 8000
            - name: mgmt
              containerPort: 8089
            - name: shc
              containerPort: 4001
            - name: kv 
              containerPort: 8191
          volumeMounts:
            - name: splunk-captain-data
              mountPath: /opt/splunk/var
            - name: splunk-captain-config
              mountPath: /opt/splunk/etc
      volumes:
        - name: splunk-captain-config
          persistentVolumeClaim:
            claimName: splunk-captain-config
        - name: splunk-captain-data
          persistentVolumeClaim:
            claimName: splunk-captain-data
