---
apiVersion: v1
kind: Service
metadata:
  name: search 
  labels:
    app: splunk
    tier: search 
spec:
  selector:
    app: splunk
    role: splunk_search_head
  ports:
    - name: splunkweb
      port: 8000
      targetPort: 8000
    - name: splunkd
      port: 8089
      targetPort: 8089
    - name: kv
      port: 8191
      targetPort: 8191
  clusterIP: None
